accounts/urls.py
# accounts/urls.py
from django.urls import path
from django.contrib.auth import views

from .views import SignUpView
from .forms import UserLoginForm

urlpatterns = [
    path('login/', views.LoginView.as_view(template_name="registration/login.html", authentication_form=UserLoginForm),
         name="login"),
    path('signup/', SignUpView.as_view(),
         name='signup'),
]

django_tweet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path("", include("tweet.urls"))
]

tweet/urls.py
# tweet/urls.py
from django.urls import path
from .views import dashboard, profile_list, profile, delete_tweet

app_name = "tweet"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("profiles/", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
    path("tweet/<int:pk>/delete", delete_tweet, name="delete")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

tweet/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch.dispatcher import receiver


# Create your models here.
class Tweet(models.Model):
    user = models.ForeignKey(
        User,  # relative to
        related_name="tweets",
        on_delete=models.DO_NOTHING
    )
    body = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # return (
        #     f"{self.user} ",
        #     f"({self.created_at:%Y-%m-%d %H:%M}): ",
        #     f"{self.body[:30]}..."
        # )
        return self.body[:30]


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",  # To
        related_name="followed_by",  # Set the related name
        symmetrical=False,
        blank=True
    )

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follows.add(instance.profile)
        user_profile.save()

# Create Profile for each new user
# post_save.connect(create_profile, sender=User)

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.contrib.auth.models import User

from django import forms


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=forms.TextInput(
        attrs={'class': 'input', 'placeholder': 'Username', 'id': 'username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'input',
            'placeholder': 'Password',
            'id': 'password',
        }
    ))


class UserSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        widgets = {
            'username': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Username'}),
        }

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        self.fields["password1"].widget = forms.PasswordInput(
            attrs={
                'class': 'input',
                'placeholder': 'Password',
            }
        )

        self.fields["password2"].widget = forms.PasswordInput(
            attrs={
                'class': 'input',
                'placeholder': 'Confirm password',
            }
        )

tweet/forms.py
from django import forms
from .models import Tweet


class TweetForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        max_length=200,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Tweet your thinking...",
                "class": "textarea is-success is-medium",
            },
        ),
        label="",
    )

    class Meta:
        model = Tweet
        exclude = ("user",)

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import UserSignUpForm


# Create your views here.
class SignUpView(generic.CreateView):
    form_class = UserSignUpForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

tweet/views.py
from django.shortcuts import render
from django import http
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from .models import Profile, Tweet
from .forms import TweetForm


# Create your views here.
@login_required()
def dashboard(request):

    if request.method == "POST":
        form = TweetForm(request.POST)
        if form.is_valid():
            tweet = form.save(commit=False)
            tweet.user = request.user
            tweet.save()
            # return http.HttpResponseRedirect('/')

    form = TweetForm()
    followed_tweets = Tweet.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    ).order_by('-id')

    return render(request, "tweet/dashboard.html", {"form": form, "tweets": followed_tweets})


def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "tweet/profile_list.html", {"profiles": profiles})


def profile(request, pk):
    profile = Profile.objects.get(id=pk)

    # Post method for this route
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")

        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()

    return render(request, "tweet/profile.html", {"profile": profile})


def delete_tweet(request, pk):
    tweet = Tweet.objects.get(id=pk)
    if not tweet:
        print("Tweet not found!")
        return http.HttpResponseRedirect(reverse_lazy("tweet:profile_list"))

    elif tweet.user != request.user:
        print("You do not have permission to delete this tweet!")
        return http.HttpResponseRedirect(reverse_lazy("tweet:profile_list"))

    else:
        tweet.delete()
        print("Tweet deleted!")
        return http.HttpResponseRedirect(reverse_lazy("tweet:dashboard"))

tweet/templates/auth_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
{% block content %}


{% endblock content %}

</body>
</html>

tweet/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tweet</title>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
<section class="hero is-small is-primary mb-4">
    <div class="hero-body">
        <h1 class="title is-1">Tweet</h1>
        <p class="subtitle is-4">A minimum - Twitter like social network built with Django</p>
    </div>
</section>
<div class="container">
    <div class="columns">

        {% block content %}


        {% endblock content %}

    </div>
</div>
</body>
</html>

tweet/templates/tweet/dashboard.html
{% extends 'base.html' %}

{% block content %}

    <div class="column">
        {% for tweet in tweets %}
            <div class="box">
                {{ tweet.body }}
                <span class="is-small has-text-grey-light">
                ({{ tweet.created_at }} by {{ tweet.user.username }})
            </span>
            </div>
        {% endfor %}
    </div>

    <div class="column is-one-third">

        <div class="block">
            <a href="{% url 'tweet:profile_list' %} ">
                <button class="button is-dark is-outlined is-fullwidth">
                    All Profiles
                </button>
            </a>
        </div>

        <div class="block">
            <a href="{% url 'tweet:profile' request.user.profile.id %} ">
                <button class="button is-success is-light is-outlined is-fullwidth">
                    My Profile
                </button>
            </a>
        </div>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button is-success is-fullwidth is-medium mt-5"
                    type="submit">Tweet
            </button>
        </form>
    </div>

{% endblock content %}

tweet/templates/tweet/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="column">

    <div class="block">
    <h1 class="title is-1">
        {{profile.user.username|upper}}'s Tweets
    </h1>
    </div>

    <form method="post">
        {% csrf_token %}
        <div class="buttons has-addons">
            {% if profile in user.profile.follows.all %}
                <button class="button is-success is-static">Follow</button>
                <button class="button is-danger" name="follow" value="unfollow">
                    Unfollow
                </button>
            {% else %}
                <button class="button is-success" name="follow" value="follow">
                    Follow
                </button>
                <button class="button is-danger is-static">Unfollow</button>
            {% endif %} 
        </div>
    </form>

    <div class="content">
        {% for tweet in profile.user.tweets.all %}
            <div class="box">
                {{ tweet.body }}
                <span class="is-small has-text-grey-light">
                    ({{ tweet.created_at }})
                </span>
            </div>
        {% endfor %}
    </div>

</div>

<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'tweet:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.follows.all %}
                <li>
                    <a href="{% url "tweet:profile" following.id %}">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url "tweet:profile" follower.id %}">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock content %}

tweet/templates/tweet/profile_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="column">
        {% for profile in profiles %}

            <div class="block">
                <div class="card"><a href="{% url "tweet:profile" profile.id %}">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-left">
                                <figure class="image is-48x48">
                                    <img src="https://bulma.io/images/placeholders/96x96.png" alt="Avatar">
                                </figure>
                            </div>
                            <div class="media-content">
                                <p class="title is-4">
                                    {{ profile.user.username }}
                                </p>
                                <p class="subtitle is-6">
                                    @{{ profile.user.username|lower }}
                                </p>
                            </div>
                        </div>
                    </div>
                </a></div>
            </div>

        {% endfor %}

    </div>

{% endblock content %}